movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'

urlpatterns = [

    path('',views.demo,name='demo'),
    path('Movie/<int:movie_id>/',views.detail,name="detail"),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL ,
                         document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
     class Meta:
         model=Movie
         fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.

from .models import Movie
from .forms import MovieForm


def demo(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)
def detail(request,movie_id):

    # fetch value
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

    # return HttpResponse("this is movie no %s" % movie_id)
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")

def update(request,id):
    movie = Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/movieapp/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the name">
  <input type="text" name="desc" placeholder="Enter the desc">
  <input type="text" name="year" placeholder="Enter the year">
  <input type="file" name="img" >
  <input type="submit" ><br>

</form>
{% endblock %}

movieproject/movieapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!--    <link rel="stylesheet" href="{% static 'style.css' %}">-->
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Online Movie Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/movieapp/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="Submit">
</form>

movieproject/movieapp/templates/detail.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->


<!--</body>-->
<!--</html>-->
{% extends 'base.html' %}
{% block body %}

<div class="'container">
    <div class="row">
        <div class="col-md-6">
          <img src="{{movie.img.url}}" width="500" height="500">
        </div>
        <div class="col-md-6" >

            <h4> {{movie.name}}</h4><br>
            <h6>{{movie.desc}}</h6>
            <h7>{{movie.year}}</h7><br></br>

            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>

        </div>

    </div>

</div>



{% endblock %}

movieproject/movieapp/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="Submit">

</form>

movieproject/movieapp/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3 ">

            <div class="card" style="width: 13rem;height:13rem">
  <img src="{{i.img.url}}"  class="card-img-top" alt=" " height="100" >
  <div class="card-body"  >
    <h5 class="card-title">{{i.name}}</h5>

    <a class='btn btn-warning' href="{% url 'movieapp:detail' i.id%}" >View details</a>

  </div>
</div>

        </div>
      {% endfor %}
    </div>

</div>








<!--{{i.id}}&ndash;&gt;{{i.name}}&ndash;&gt;{{i.desc}}&ndash;&gt;{{i.year}}<br>-->
<!--<a href="movie/{{i.id}}">{{i.name}}<br></a>-->


{% endblock %}